rosparam set /main_database_grasp_from_library/dir_path_database data/deep_learning/grasp-database/
rosparam set /main_database_grasp_from_library/database_name dl_grasp_database

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/After_Learning_1/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/After_Learning_1/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch


rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/Learning_Spraycan/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/Learning_Spraycan/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch


rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/Without_learning_2/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/Without_learning_2/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/Without_learning_Spraycan/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/ICRA_MATCHING/Without_learning_Spraycan/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch


rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/After_Learning_Mine_Broke_up/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/After_Learning_Mine_Broke_up/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch


rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Learning_Spraycan_1/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Learning_Spraycan_1/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Learning_Spraycan_2/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Learning_Spraycan_2/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Learning_Spraycan_3_Only_Fails/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Learning_Spraycan_3_Only_Fails/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch


rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Without_Learning_Mine_1/library_positives
rosparam set /main_database_grasp_from_library/success 1
roslaunch grasp_template_planning main_database_grasp_from_library.launch

rosparam set /main_database_grasp_from_library/dir_path_bagfiles data/migrated_logs_local/12-07-PR2-Template-Grasping-Experiment-Logs/PARTIALLY_NORMED_DISTANCE/Without_Learning_Mine_1/library_negatives
rosparam set /main_database_grasp_from_library/success 0
roslaunch grasp_template_planning main_database_grasp_from_library.launch
