"""autogenerated by genpy from task_recorder2_srvs/GetInfoRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import task_recorder2_msgs.msg

class GetInfoRequest(genpy.Message):
  _md5sum = "051ab68fd5c4bb308007078efebe4301"
  _type = "task_recorder2_srvs/GetInfoRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """task_recorder2_msgs/Description description

================================================================================
MSG: task_recorder2_msgs/Description
string SIDE_GRASP=side_grasp
string TOP_GRASP=top_grasp
string PLACING=placing
string RELEASING=releasing
string TURN_ON_DRILL=turn_on_drill
string DRILLING=drilling
string description
int32 id
int32 trial

"""
  __slots__ = ['description']
  _slot_types = ['task_recorder2_msgs/Description']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       description

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetInfoRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.description is None:
        self.description = task_recorder2_msgs.msg.Description()
    else:
      self.description = task_recorder2_msgs.msg.Description()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.description.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i.pack(_x.description.id, _x.description.trial))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.description is None:
        self.description = task_recorder2_msgs.msg.Description()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.description.description = str[start:end].decode('utf-8')
      else:
        self.description.description = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.description.id, _x.description.trial,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.description.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i.pack(_x.description.id, _x.description.trial))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.description is None:
        self.description = task_recorder2_msgs.msg.Description()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.description.description = str[start:end].decode('utf-8')
      else:
        self.description.description = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.description.id, _x.description.trial,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i = struct.Struct("<2i")
"""autogenerated by genpy from task_recorder2_srvs/GetInfoResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class GetInfoResponse(genpy.Message):
  _md5sum = "e0d469569497a25067a1a1fcb8216973"
  _type = "task_recorder2_srvs/GetInfoResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool is_recording
time first_recorded_time_stamp
time last_recorded_time_stamp
float64 sampling_rate
string file_name
string info
int32 return_code
int32 SERVICE_CALL_FAILED = 0
int32 SERVICE_CALL_SUCCESSFUL = 1

"""
  # Pseudo-constants
  SERVICE_CALL_FAILED = 0
  SERVICE_CALL_SUCCESSFUL = 1

  __slots__ = ['is_recording','first_recorded_time_stamp','last_recorded_time_stamp','sampling_rate','file_name','info','return_code']
  _slot_types = ['bool','time','time','float64','string','string','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_recording,first_recorded_time_stamp,last_recorded_time_stamp,sampling_rate,file_name,info,return_code

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetInfoResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.is_recording is None:
        self.is_recording = False
      if self.first_recorded_time_stamp is None:
        self.first_recorded_time_stamp = genpy.Time()
      if self.last_recorded_time_stamp is None:
        self.last_recorded_time_stamp = genpy.Time()
      if self.sampling_rate is None:
        self.sampling_rate = 0.
      if self.file_name is None:
        self.file_name = ''
      if self.info is None:
        self.info = ''
      if self.return_code is None:
        self.return_code = 0
    else:
      self.is_recording = False
      self.first_recorded_time_stamp = genpy.Time()
      self.last_recorded_time_stamp = genpy.Time()
      self.sampling_rate = 0.
      self.file_name = ''
      self.info = ''
      self.return_code = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4Id.pack(_x.is_recording, _x.first_recorded_time_stamp.secs, _x.first_recorded_time_stamp.nsecs, _x.last_recorded_time_stamp.secs, _x.last_recorded_time_stamp.nsecs, _x.sampling_rate))
      _x = self.file_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_i.pack(self.return_code))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.first_recorded_time_stamp is None:
        self.first_recorded_time_stamp = genpy.Time()
      if self.last_recorded_time_stamp is None:
        self.last_recorded_time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.is_recording, _x.first_recorded_time_stamp.secs, _x.first_recorded_time_stamp.nsecs, _x.last_recorded_time_stamp.secs, _x.last_recorded_time_stamp.nsecs, _x.sampling_rate,) = _struct_B4Id.unpack(str[start:end])
      self.is_recording = bool(self.is_recording)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.file_name = str[start:end].decode('utf-8')
      else:
        self.file_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.info = str[start:end].decode('utf-8')
      else:
        self.info = str[start:end]
      start = end
      end += 4
      (self.return_code,) = _struct_i.unpack(str[start:end])
      self.first_recorded_time_stamp.canon()
      self.last_recorded_time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4Id.pack(_x.is_recording, _x.first_recorded_time_stamp.secs, _x.first_recorded_time_stamp.nsecs, _x.last_recorded_time_stamp.secs, _x.last_recorded_time_stamp.nsecs, _x.sampling_rate))
      _x = self.file_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_i.pack(self.return_code))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.first_recorded_time_stamp is None:
        self.first_recorded_time_stamp = genpy.Time()
      if self.last_recorded_time_stamp is None:
        self.last_recorded_time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.is_recording, _x.first_recorded_time_stamp.secs, _x.first_recorded_time_stamp.nsecs, _x.last_recorded_time_stamp.secs, _x.last_recorded_time_stamp.nsecs, _x.sampling_rate,) = _struct_B4Id.unpack(str[start:end])
      self.is_recording = bool(self.is_recording)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.file_name = str[start:end].decode('utf-8')
      else:
        self.file_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.info = str[start:end].decode('utf-8')
      else:
        self.info = str[start:end]
      start = end
      end += 4
      (self.return_code,) = _struct_i.unpack(str[start:end])
      self.first_recorded_time_stamp.canon()
      self.last_recorded_time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_B4Id = struct.Struct("<B4Id")
class GetInfo(object):
  _type          = 'task_recorder2_srvs/GetInfo'
  _md5sum = '8be8f941c846b9a72a2bc6daeaa0a99f'
  _request_class  = GetInfoRequest
  _response_class = GetInfoResponse
