qpOASES3.0beta: include/qpOASES/Utils.ipp File Reference
include/qpOASES/Utils.ipp File Reference
Functions
BEGIN_NAMESPACE_QPOASES real_t getSign (real_t arg)
int getMax (int x, int y)
int getMin (int x, int y)
real_t getMax (real_t x, real_t y)
real_t getMin (real_t x, real_t y)
real_t getAbs (real_t x)
Detailed Description
Author:
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version:
3.0beta
Date:
2007-2012
Implementation of some inlined utilities for working with the different QProblem classes.
Function Documentation
real_t getAbs (real_t x) [inline]
Returns the absolute value of a real number.
Returns:
Absolute value of a real number
Parameters:
x Real number.
Referenced by QProblem::addBound_checkLI(), QProblem::addConstraint_checkLI(), QProblemB::backsolveR(), QProblem::backsolveT(), QProblemB::determineDataShift(), QProblem::determineDataShift(), QProblemB::determineHessianType(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getMaxKKTviolation(), QProblemB::hotstart(), QProblem::hotstart(), QProblem::performRamping(), QProblem::performStep(), QProblemB::relativeHomotopyLength(), QProblem::relativeHomotopyLength(), QProblem::solveInitialQP(), and QProblem::solveQP().
int getMax (int x, int y) [inline]
Returns maximum of two integers.
Returns:
Maximum of two integers
Parameters:
x First integer.
y Second integer.
Referenced by QProblem::ensureNonzeroCurvature(), QProblemB::hotstart(), QProblem::hotstart(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), DenseMatrix::times(), and DenseMatrix::transTimes().
real_t getMax (real_t x, real_t y) [inline]
Returns maximum of two reals.
Returns:
Maximum of two reals
Parameters:
x First real_t.
y Second real_t.
int getMin (int x, int y) [inline]
Returns minimum of two integers.
Returns:
Minimum of two integers
Parameters:
x First integer.
y Second integer.
Referenced by QProblemB::hotstart(), QProblem::hotstart(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), and QProblem::QProblem().
real_t getMin (real_t x, real_t y) [inline]
Returns minimum of two reals.
Returns:
Minimum of two reals
Parameters:
x First real_t.
y Second real_t.
BEGIN_NAMESPACE_QPOASES real_t getSign (real_t arg) [inline]
Returns sign of a real_t-valued argument.
Returns:
1.0: argument is non-negative
-1.0: argument is negative
Parameters:
arg Double-valued argument whose sign is to be determined.