qpOASES3.0beta: include/qpOASES/Utils.hpp File Reference
include/qpOASES/Utils.hpp File Reference
#include <qpOASES/MessageHandling.hpp>
#include <qpOASES/Utils.ipp>
Functions
BEGIN_NAMESPACE_QPOASES returnValue print (const real_t *const v, int n)
returnValue print (const real_t *const v, int n, const int *const V_idx)
returnValue print (const real_t *const v, int n, const char *name)
returnValue print (const real_t *const M, int nrow, int ncol)
returnValue print (const real_t *const M, int nrow, int ncol, const int *const ROW_idx, const int *const COL_idx)
returnValue print (const real_t *const M, int nrow, int ncol, const char *name)
returnValue print (const int *const index, int n)
returnValue print (const int *const index, int n, const char *name)
returnValue myPrintf (const char *s)
returnValue printCopyrightNotice ()
returnValue readFromFile (real_t *data, int nrow, int ncol, const char *datafilename)
returnValue readFromFile (real_t *data, int n, const char *datafilename)
returnValue readFromFile (int *data, int n, const char *datafilename)
returnValue writeIntoFile (const real_t *const data, int nrow, int ncol, const char *datafilename, BooleanType append)
returnValue writeIntoFile (const real_t *const data, int n, const char *datafilename, BooleanType append)
returnValue writeIntoFile (const int *const integer, int n, const char *datafilename, BooleanType append)
real_t getCPUtime ()
real_t getNorm (const real_t *const v, int n)
real_t getSign (real_t arg)
int getMax (int x, int y)
int getMin (int x, int y)
real_t getMax (real_t x, real_t y)
real_t getMin (real_t x, real_t y)
real_t getAbs (real_t x)
void getKKTResidual (int nV, int nC, const real_t *const H, const real_t *const g, const real_t *const A, const real_t *const lb, const real_t *const ub, const real_t *const lbA, const real_t *const ubA, const real_t *const x, const real_t *const y, real_t &stat, real_t &feas, real_t &cmpl)
returnValue convertBooleanTypeToString (BooleanType value, char *const string)
returnValue convertSubjectToStatusToString (SubjectToStatus value, char *const string)
returnValue convertPrintLevelToString (PrintLevel value, char *const string)
Detailed Description
Author:
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version:
3.0beta
Date:
2007-2012
Declaration of some utilities for working with the different QProblem classes.
Function Documentation
returnValue convertBooleanTypeToString (BooleanType value, char *const string)
Writes a value of BooleanType into a string.
Returns:
SUCCESSFUL_RETURN
Parameters:
value Value to be written.
string Input: String of sufficient size,
Output: String containing value.
References BT_TRUE, and SUCCESSFUL_RETURN.
Referenced by Options::print().
returnValue convertPrintLevelToString (PrintLevel value, char *const string)
Writes a value of PrintLevel into a string.
Returns:
SUCCESSFUL_RETURN
Parameters:
value Value to be written.
string Input: String of sufficient size,
Output: String containing value.
References PL_HIGH, PL_LOW, PL_MEDIUM, PL_NONE, PL_TABULAR, and SUCCESSFUL_RETURN.
Referenced by Options::print().
returnValue convertSubjectToStatusToString (SubjectToStatus value, char *const string)
Writes a value of SubjectToStatus into a string.
Returns:
SUCCESSFUL_RETURN
Parameters:
value Value to be written.
string Input: String of sufficient size,
Output: String containing value.
References ST_INACTIVE, ST_LOWER, ST_UNDEFINED, ST_UPPER, and SUCCESSFUL_RETURN.
Referenced by Options::print().
real_t getAbs (real_t x) [inline]
Returns the absolute value of a real number.
Returns:
Absolute value of a real number
Parameters:
x Real number.
Referenced by QProblem::addBound_checkLI(), QProblem::addConstraint_checkLI(), QProblemB::backsolveR(), QProblem::backsolveT(), QProblemB::determineDataShift(), QProblem::determineDataShift(), QProblemB::determineHessianType(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getMaxKKTviolation(), QProblemB::hotstart(), QProblem::hotstart(), QProblem::performRamping(), QProblem::performStep(), QProblemB::relativeHomotopyLength(), QProblem::relativeHomotopyLength(), QProblem::solveInitialQP(), and QProblem::solveQP().
real_t getCPUtime ()
Returns the current system time.
Returns:
current system time
References real_t.
Referenced by SQProblem::hotstart(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::isCPUtimeLimitExceeded(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::solveQP(), and QProblemB::solveQP().
void getKKTResidual (int nV, int nC, const real_t *const H, const real_t *const g, const real_t *const A, const real_t *const lb, const real_t *const ub, const real_t *const lbA, const real_t *const ubA, const real_t *const x, const real_t *const y, real_t & stat, real_t & feas, real_t & cmpl)
Computes "residual" of KKT system.
Parameters:
nV Number of variables.
nC Number of constraints.
H Hessian matrix.
g Sequence of gradient vectors.
A Constraint matrix.
lb Sequence of lower bound vectors (on variables).
ub Sequence of upper bound vectors (on variables).
lbA Sequence of lower constraints' bound vectors.
ubA Sequence of upper constraints' bound vectors.
x Sequence of primal trial vectors.
y Sequence of dual trial vectors.
stat Maximum value of stationarity condition residual.
feas Maximum value of primal feasibility violation.
cmpl Maximum value of complementarity residual.
References EPS, and real_t.
Referenced by solveOQPbenchmark().
int getMax (int x, int y) [inline]
Returns maximum of two integers.
Returns:
Maximum of two integers
Parameters:
x First integer.
y Second integer.
Referenced by QProblem::ensureNonzeroCurvature(), QProblemB::hotstart(), QProblem::hotstart(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), DenseMatrix::times(), and DenseMatrix::transTimes().
real_t getMax (real_t x, real_t y) [inline]
Returns maximum of two reals.
Returns:
Maximum of two reals
Parameters:
x First real_t.
y Second real_t.
int getMin (int x, int y) [inline]
Returns minimum of two integers.
Returns:
Minimum of two integers
Parameters:
x First integer.
y Second integer.
Referenced by QProblemB::hotstart(), QProblem::hotstart(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), and QProblem::QProblem().
real_t getMin (real_t x, real_t y) [inline]
Returns minimum of two reals.
Returns:
Minimum of two reals
Parameters:
x First real_t.
y Second real_t.
real_t getNorm (const real_t *const v, int n)
Returns the Euclidean norm of a vector.
Returns:
0: successful
Parameters:
v Vector.
n Vector's dimension.
References real_t.
real_t getSign (real_t arg) [inline]
Returns sign of a real_t-valued argument.
Returns:
1.0: argument is non-negative
-1.0: argument is negative
Parameters:
arg Double-valued argument whose sign is to be determined.
returnValue myPrintf (const char * s)
Prints a string to desired output target (useful also for MATLAB output!).
Returns:
SUCCESSFUL_RETURN
Parameters:
s String to be written.
References getGlobalMessageHandler(), MessageHandling::getOutputFile(), RET_NO_GLOBAL_MESSAGE_OUTPUTFILE, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by MessageHandling::listAllMessages(), print(), Options::print(), Constraints::print(), Bounds::print(), printCopyrightNotice(), QProblemB::printIteration(), QProblem::printIteration(), QProblemB::printProperties(), QProblem::printProperties(), and MessageHandling::throwMessage().
BEGIN_NAMESPACE_QPOASES returnValue print (const real_t *const v, int n)
Prints a vector.
Returns:
SUCCESSFUL_RETURN
Parameters:
v Vector to be printed.
n Length of vector.
References myPrintf(), and SUCCESSFUL_RETURN.
Referenced by print().
returnValue print (const real_t *const v, int n, const int *const V_idx)
Prints a permuted vector.
Returns:
SUCCESSFUL_RETURN
Parameters:
v Vector to be printed.
n Length of vector.
V_idx Pemutation vector.
References myPrintf(), and SUCCESSFUL_RETURN.
returnValue print (const real_t *const v, int n, const char * name)
Prints a named vector.
Returns:
SUCCESSFUL_RETURN
Parameters:
v Vector to be printed.
n Length of vector.
name Name of vector.
References myPrintf(), and print().
returnValue print (const real_t *const M, int nrow, int ncol)
Prints a matrix.
Returns:
SUCCESSFUL_RETURN
Parameters:
M Matrix to be printed.
nrow Row number of matrix.
ncol Column number of matrix.
References myPrintf(), print(), and SUCCESSFUL_RETURN.
returnValue print (const real_t *const M, int nrow, int ncol, const int *const ROW_idx, const int *const COL_idx)
Prints a permuted matrix.
Returns:
SUCCESSFUL_RETURN
Parameters:
M Matrix to be printed.
nrow Row number of matrix.
ncol Column number of matrix.
ROW_idx Row pemutation vector.
COL_idx Column pemutation vector.
References myPrintf(), print(), and SUCCESSFUL_RETURN.
returnValue print (const real_t *const M, int nrow, int ncol, const char * name)
Prints a named matrix.
Returns:
SUCCESSFUL_RETURN
Parameters:
M Matrix to be printed.
nrow Row number of matrix.
ncol Column number of matrix.
name Name of matrix.
References myPrintf(), and print().
returnValue print (const int *const index, int n)
Prints an index array.
Returns:
SUCCESSFUL_RETURN
Parameters:
index Index array to be printed.
n Length of index array.
References myPrintf(), and SUCCESSFUL_RETURN.
returnValue print (const int *const index, int n, const char * name)
Prints a named index array.
Returns:
SUCCESSFUL_RETURN
Parameters:
index Index array to be printed.
n Length of index array.
name Name of index array.
References myPrintf(), and print().
returnValue printCopyrightNotice ()
Prints qpOASES copyright notice.
Returns:
SUCCESSFUL_RETURN
References myPrintf(), and SUCCESSFUL_RETURN.
Referenced by QProblemB::QProblemB().
returnValue readFromFile (real_t * data, int nrow, int ncol, const char * datafilename)
Reads a real_t matrix from file.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
RET_UNABLE_TO_READ_FILE
Parameters:
data Matrix to be read from file.
nrow Row number of matrix.
ncol Column number of matrix.
datafilename Data file name.
References __FILE__, __FUNCTION__, __LINE__, getGlobalMessageHandler(), real_t, RET_NOT_YET_IMPLEMENTED, RET_UNABLE_TO_OPEN_FILE, RET_UNABLE_TO_READ_FILE, SUCCESSFUL_RETURN, MessageHandling::throwError(), and VS_VISIBLE.
Referenced by SQProblem::hotstart(), QProblemB::loadQPvectorsFromFile(), QProblem::loadQPvectorsFromFile(), readFromFile(), readOQPdata(), readOQPdimensions(), QProblemB::setupQPdataFromFile(), and QProblem::setupQPdataFromFile().
returnValue readFromFile (real_t * data, int n, const char * datafilename)
Reads a real_t vector from file.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
RET_UNABLE_TO_READ_FILE
Parameters:
data Vector to be read from file.
n Length of vector.
datafilename Data file name.
References readFromFile().
returnValue readFromFile (int * data, int n, const char * datafilename)
Reads an integer (column) vector from file.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
RET_UNABLE_TO_READ_FILE
Parameters:
data Vector to be read from file.
n Length of vector.
datafilename Data file name.
References __FILE__, __FUNCTION__, __LINE__, getGlobalMessageHandler(), RET_NOT_YET_IMPLEMENTED, RET_UNABLE_TO_OPEN_FILE, RET_UNABLE_TO_READ_FILE, SUCCESSFUL_RETURN, MessageHandling::throwError(), and VS_VISIBLE.
returnValue writeIntoFile (const real_t *const data, int nrow, int ncol, const char * datafilename, BooleanType append)
Writes a real_t matrix into a file.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
Parameters:
data Matrix to be written into file.
nrow Row number of matrix.
ncol Column number of matrix.
datafilename Data file name.
append Indicates if data shall be appended if the file already exists (otherwise it is overwritten).
References __FILE__, __FUNCTION__, __LINE__, BT_TRUE, getGlobalMessageHandler(), RET_NOT_YET_IMPLEMENTED, RET_UNABLE_TO_OPEN_FILE, SUCCESSFUL_RETURN, MessageHandling::throwError(), and VS_VISIBLE.
Referenced by writeIntoFile().
returnValue writeIntoFile (const real_t *const data, int n, const char * datafilename, BooleanType append)
Writes a real_t vector into a file.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
Parameters:
data Vector to be written into file.
n Length of vector.
datafilename Data file name.
append Indicates if data shall be appended if the file already exists (otherwise it is overwritten).
References writeIntoFile().
returnValue writeIntoFile (const int *const integer, int n, const char * datafilename, BooleanType append)
Writes an integer (column) vector into a file.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
Parameters:
integer Integer vector to be written into file.
n Length of vector.
datafilename Data file name.
append Indicates if integer shall be appended if the file already exists (otherwise it is overwritten).
References __FILE__, __FUNCTION__, __LINE__, BT_TRUE, getGlobalMessageHandler(), RET_NOT_YET_IMPLEMENTED, RET_UNABLE_TO_OPEN_FILE, SUCCESSFUL_RETURN, MessageHandling::throwError(), and VS_VISIBLE.