string board

int32 action
int32 UPDATE_AND_CHANGE_COLOR=0
int32 CHANGE_COLOR=1

string key
string RECORDING_KEY=recording
string STREAMING_KEY=streaming
string SETUP_KEY=setup
string CONTROL_KEY=setup

string value
string STARTING_VALUE=starting
string STARTED_VALUE=started
string STOPPING_VALUE=stopping
string STOPPED_VALUE=stopped
string FAILED_VALUE=failed

string ACTIVE_VALUE=active
string FROZEN_VALUE=frozen

int32 color
int32 WHITE=0
int32 GREEN=1
int32 YELLOW=2
int32 RED=3
int32 PURPLE=4
int32 NUM_COLORS=5